apiVersion: v1
kind: Pod
metadata:
  name: worker-app
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: worker-app
      image: odekloud/examplevotingapp_worker:v1
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"